DIAM-Project-FlavorNetwork-master/flavornetwork/flavornetwork/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('network/', include(('network.urls', 'network'), namespace='network')),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG:
#    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DIAM-Project-FlavorNetwork-master/flavornetwork/network/urls.py
from django.urls import path
from . import views
from .views import UserListView, get_user_detail

# Namespace for your application.
# This allows you to organize URLs by application and use the name when referring to them.
app_name = 'network'

urlpatterns = [
    # Endpoint to retrieve a list of all users.
    path('api/users/', UserListView.as_view(), name='user-list'),
    # Endpoint to create a new message.
    path('api/messages/', views.create_message, name='create-message'),
    # Endpoint to retrieve all messages related to a specific user, either sent or received.
    path('api/messages/by_user/', views.get_user_messages, name='get_user_messages'),
    # Endpoint to retrieve detailed information about a specific user by their ID.
    path('api/users/<int:pk>/', get_user_detail, name='user-detail'),
    # Home page URL. This is the root URL for the application.
    path("", views.index, name="index"),
    # User registration URL. It shows the registration form and processes the user registration.
    path('register/', views.register, name='register'),
    # Login URL. It shows the login form and logs the user in.
    path('login/', views.user_login, name='login'),
    # Logout URL. It logs the user out.
    path('logout/', views.user_logout, name='logout'),
    # User profile URL. It displays the profile of the logged-in user.
    path('profile/', views.profile, name='profile'),
    # Edit profile URL. It shows the form to edit the user's profile and saves the changes.
    path('edit-profile/', views.edit_profile, name='edit-profile'),
    # Add recipe URL. It displays the form to create a new recipe and adds it to the database.
    path('add-recipe/', views.add_recipe, name='add-recipe'),
    # View recipe details URL. It takes a recipe ID and displays the recipe's details.
    path('recipes/<int:recipe_id>/', views.view_recipe, name='view-recipe'),
    # View user cookbook URL. It takes a user ID and displays their cookbook.
    path('cookbook/<int:user_id>/', views.view_cookbook, name='view-cookbook'),
    # Edit recipe URL. It takes a recipe ID, shows the form to edit the recipe, and saves the changes.
    path('recipe/<int:recipe_id>/edit/', views.edit_recipe, name='edit-recipe'),
    # View favorites URL. It displays a list of the user's favorite recipes.
    path('favorites/', views.view_favorites, name='view-favorites'),
    # Add to favorites URL. It takes a recipe ID and adds the recipe to the user's favorites.
    path('recipe/<int:recipe_id>/add_to_favorites/', views.add_to_favorites, name='add-to-favorites'),
    # Remove from favorites URL. It takes a recipe ID and removes the recipe from the user's favorites.
    path('recipe/<int:recipe_id>/remove_from_favorites/', views.remove_from_favorites, name='remove-from-favorites'),
    # Delete recipe URL. It takes a recipe ID, allows only the creator or an admin to delete it,
    # and then redirects to an appropriate page after deletion.
    path('recipe/<int:recipe_id>/delete/', views.delete_recipe, name='delete-recipe'),
    # This URL endpoint directs to the 'feed' view which displays the user's feed.
    path('feed/', views.feed, name='feed'),
    # Add challenge URL. Allows superusers to create new cooking challenges.
    path('add-challenge/', views.add_challenge, name='add-challenge'),
    # View challenge details URL. It takes a challenge ID and displays details including its recipes,
    # and allows authenticated users to submit their recipes to the challenge.
    path('challenges/<int:challenge_id>/', views.view_challenge, name='view-challenge'),
    # This URL directs to a view that allows superusers to manage challenges,
    # typically listing them with options to edit or delete.
    path('manage-challenges/', views.manage_challenges, name='manage-challenges'),
    # This URL directs to the edit page for a specific challenge.
    path('challenge/<int:challenge_id>/edit/', views.edit_challenge, name='edit-challenge'),
    # This URL handles the deletion of a challenge based on a POST request.
    # The view will check if the user is a superuser before allowing the challenge to be deleted.
    path('challenge/delete/', views.delete_challenge, name='delete-challenge'),
    # This URL directs to a view that lists all the users, allowing superusers to manage user accounts.
    path('manage-users/', views.manage_users, name='manage-users'),
    # This URL handles the deletion of a user.
    path('delete-user/', views.delete_user, name='delete-user'),
    # This URL handles the rating of a recipe
    path('recipes/<int:recipe_id>/rate/', views.rate_recipe, name='rate-view'),
    # This URL handles the remove of a recipe from a challenge
    path('challenges/<int:challenge_id>/remove-recipe/<int:recipe_id>/', views.remove_recipe_from_challenge, name='remove-recipe-from-challenge'),
]

DIAM-Project-FlavorNetwork-master/flavornetwork/network/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from .forms import UserRegistrationForm, RecipeSubmissionForm, ChallengeForm
from django.shortcuts import render, redirect
from .forms import UserRegistrationForm
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .forms import ProfileForm
from .models import Profile, Cookbook, Favorite, RecipeChallenge, Challenge, Rating
from .forms import RecipeForm
from .models import Recipe, User
from django.contrib.auth.decorators import user_passes_test
from django.utils import timezone
from django.http import HttpResponseNotAllowed
from django.core.paginator import Paginator
from django.db.models import Avg
from .forms import CommentForm
from .models import Comment
from rest_framework import status
from rest_framework.decorators import api_view, permission_classes
from rest_framework.response import Response
from .models import Message
from .serializers import MessageSerializer
from django.contrib.auth.models import User
from rest_framework import generics
from rest_framework.permissions import IsAuthenticated
from .serializers import UserSerializer


# This function checks if the provided user object has the necessary attributes
# and permissions to be considered a superuser.
def is_superuser(user):
    return user.is_authenticated and user.is_superuser


# The home page view.
@login_required(login_url='network:login')
def index(request):
    # Fetch only recipes that are marked as 'published'.
    published_recipes = Recipe.objects.filter(status='published')

    # Fetch challenges that are currently active based on the current UTC time.
    #challenges = Challenge.objects.filter(start_date__lte=timezone.now(), end_date__gte=timezone.now())
    challenges = Challenge.objects.order_by('id')[:10]

    # Renders the index page template.
    return render(request, 'network/index.html', {
        'published_recipes': published_recipes,
        'profile': request.user.profile,
        'challenges': challenges,
    })


# Handles user registration with a custom form that includes additional fields like first and last name.
def register(request):
    if request.method == 'POST':
        # If the form is submitted (POST request) bind the POST data to the UserRegistrationForm.
        form = UserRegistrationForm(request.POST)
        # Check if the form is valid (all required fields are filled and valid).
        if form.is_valid():
            # If valid, create a User object from the form, but don't save to the database yet.
            user = form.save(commit=False)
            # Manually set the first_name from the form's cleaned data.
            user.first_name = form.cleaned_data.get('first_name')
            # Manually set the last_name from the form's cleaned data.
            user.last_name = form.cleaned_data.get('last_name')
            # Save the User object to the database.
            user.save()
            # Authenticate the user using the provided credentials.
            user = authenticate(username=user.username, password=request.POST['password1'])
            # Log the user in (creating a user session).
            login(request, user)

            # Redirect the user to the index page after successful registration.
            return redirect('network:index')
    else:
        # If not a POST request, instantiate a new, blank UserRegistrationForm.
        form = UserRegistrationForm()
    # Render the registration page template with the UserRegistrationForm.
    return render(request,  'network/register.html', {
        'form': form,
    })


# Manages user login using the built-in AuthenticationForm.
def user_login(request):
    # If the request is a POST, attempt to process the form data.
    if request.method == 'POST':
        # Create an instance of the AuthenticationForm with the request data.
        form = AuthenticationForm(request, data=request.POST)
        # Check if the form is valid (username and password correct).
        if form.is_valid():
            # Retrieve the username and password from the form data.
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            # Authenticate the user against the database.
            user = authenticate(username=username, password=password)
            # If the user object is not None, the credentials are valid.
            if user is not None:
                login(request, user)  # Log the user in.
                return HttpResponseRedirect(reverse('network:index'))  # Redirect to the index page.
            else:
                # If credentials are not valid, display an error message.
                messages.error(request, 'Invalid username or password.')
        else:
            # If form is not valid, display an error message.
            messages.error(request, 'Invalid username or password.')
    else:
        # If the request is not POST, display the login form.
        form = AuthenticationForm()
    # Render the login page with the AuthenticationForm.

    return render(request,  'network/login.html', {
        'form': form,
    })


# Logs out the current user and redirects to the home page.
@login_required(login_url='network:login')
def user_logout(request):
    logout(request)  # Log the user out.
    return HttpResponseRedirect(reverse('network:login'))  # Redirect to the index page.


# Displays the profile of the currently logged-in user.
@login_required(login_url='network:login')
def profile(request):
    # The user data is automatically included in the request, no need to fetch from database manually.
    return render(request,  'network/profile.html', {
        'profile': request.user.profile,
    })


# Allows users to edit their profile information.
@login_required(login_url='network:login')
def edit_profile(request):
    # Attempt to retrieve the user's profile or create a new one if it does not exist.
    try:
        profile = request.user.profile
    except Profile.DoesNotExist:
        # If the user does not have a profile, create a new one.
        profile = Profile.objects.create(user=request.user)

    # Check if the form submission is a POST request.
    if request.method == 'POST':
        # Create a form instance populated with the POST data and files, linked to the user's profile.
        form = ProfileForm(request.POST, request.FILES, instance=profile)
        # Validate the form.
        if form.is_valid():
            # Save the valid form data to the database.
            form.save()
            # Display a success message to the user.
            messages.success(request, 'Profile updated successfully!')
            # Redirect the user to the profile page after successful update.
            return redirect('network:profile')
    else:
        # If the request is not POST, display the form with existing profile data.
        form = ProfileForm(instance=profile)

    profile = request.user.profile
    # Render the edit profile page with the profile form.
    return render(request,  'network/edit_profile.html', {
        'form': form,
        'profile': profile,
    })


# Enables the user to add a new recipe to the system.
@login_required(login_url='network:login')
def add_recipe(request):
    # Try to retrieve an existing cookbook for the user or create a new one if it does not exist.
    try:
        cookbook = Cookbook.objects.get(user=request.user, title="Cookbook")
    except Cookbook.DoesNotExist:
        # If no cookbook exists for the user, create a new one with a title "Cookbook".
        cookbook = Cookbook.objects.create(user=request.user, title="Cookbook")

    # Check if the form has been submitted (i.e., the request is a POST request).
    if request.method == 'POST':
        # Create a form instance and populate it with data from the request (binding data).
        form = RecipeForm(request.POST, request.FILES)
        # Check if the form is valid (all required fields are filled and valid).
        if form.is_valid():
            # Save the recipe form to create a new Recipe object but don't commit to the database yet.
            recipe = form.save(commit=False)
            # Assign the current user as the creator of the recipe.
            recipe.user = request.user
            # Save the Recipe object to the database.
            recipe.save()
            # Add the newly created recipe to the user's cookbook.
            cookbook.recipes.add(recipe)
            # Redirect to the cookbook of the user after successful recipe creation.
            return redirect('network:view-cookbook', user_id=request.user.id)
    else:
        # If the request is not a POST request, initialize a blank form.
        form = RecipeForm()

    profile = request.user.profile
    # Render the add_recipe.html template with the recipe form.
    return render(request,  'network/add_recipe.html', {
        'form': form,
        'profile': request.user.profile,
    })


# This view function retrieves and displays details of a specific recipe.
@login_required(login_url='network:login')
def view_recipe(request, recipe_id):
    # Retrieve the Recipe object or show a 404 if not found.
    recipe = get_object_or_404(Recipe, pk=recipe_id)

    # Check if the current recipe is a favorite of the logged-in user.
    is_favorite = Favorite.objects.filter(user=request.user, recipe=recipe).exists()

    # Aggregate and calculate the average rating for the recipe.
    average_rating_result = Rating.objects.filter(recipe=recipe).aggregate(Avg('score'))
    average_rating = average_rating_result['score__avg'] or 0

DIAM-Project-FlavorNetwork-master/flavornetwork/network/templates/network/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    {% load static %}

    <script src="{% static 'network/scripts/scripts.js' %}?{% now 'U' %}"></script>
    <title>{% block title %}Flavor Network{% endblock %}</title>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link href="{% static 'network/css/styles.css' %}?{% now 'U' %}" rel="stylesheet" type="text/css">
</head>

<body>
{% block header %}
    <header>
        <div id="{% block top-bar-class %}top-bar{% endblock %}">

            {% block header-menu %}
                <nav id="nav-bar" class="navbar navbar-expand-lg justify-content-between">
                    <div class="d-flex">
                        <img src="{% static 'network/images/logo-2.png' %}" alt="Flavor Network" style="max-height: 50px;">
                    </div>

                    <div class="d-flex justify-content-center flex-grow-1">
                        <a href="{% url 'network:index' %}">Home</a>
                        <a href="{% url 'network:feed' %}">Feed</a>
                        {% if request.user.is_authenticated %}
                            <a href="{% url 'network:view-cookbook' user.id %}">Cookbook</a>
                            <a href="{% url 'network:view-favorites' %}">Favorites</a>
                        {% endif %}
                    </div>

                    <div class="d-flex justify-content-end">

                        <div class="dropdown">
                            <a href="#" class="dropdown-toggle" id="userDropdown" data-bs-toggle="dropdown" aria-expanded="false">
                                <img src="{{ profile.image.url }}" alt="{{ profile.user.username }}" width="50" height="50" class="rounded-circle">
                            </a>
                            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="userDropdown">
                                <li><a class="dropdown-item" href="{% url 'network:profile' %}">Profile</a></li>
                                <li><a class="dropdown-item" href="{% url 'network:logout' %}">Logout</a></li>
                                {% if user.is_superuser %}
                                    <li><a href="{% url 'network:manage-users' %}">Manage Users</a></li>
                                    <li><a href="{% url 'network:add-challenge' %}">Add Challenge</a></li>
                                    <li><a href="{% url 'network:manage-challenges' %}">Manage Challenges</a></li>
                                {% endif %}

                            </ul>
                        </div>


                    </div>
                </nav>
            {% endblock %}

        </div>
    </header>
{% endblock %}

<div id="{% block main-container-div %}main-container{% endblock %}">

    {% block feed %}
    {% endblock %}

</div>

</body>
</html>

<script>
    $( ".dropdown-toggle" ).click(function() {
        if ( $('#home-div').hasClass('normal') ) {
            $('#home-div').removeClass('normal').addClass('open');
        } else {
            $('#home-div').removeClass('open').addClass('normal');
        }
    });
</script>

DIAM-Project-FlavorNetwork-master/flavornetwork/network/templates/network/feed.html
{% extends "network/base.html" %}
{% load static %}

{% block title %}Feed{% endblock %}

{% block feed %}
<div class="home-div" style="position: relative;">
    <div id="feed-content" class="container mt-4" style="margin-right: 0; margin-left: 0; width: 100%;">
        {% for recipe in page_obj %}
        <div class="row mb-4 h-100">
            <!-- Recipe Image -->
            <div class="col-7">
                {% if recipe.images %}
                <img src="{{ recipe.images.url }}" alt="{{ recipe.title }}" class="recipe-image img-fluid">
                {% else %}
                <p class="text-center">Image not available</p>
                {% endif %}
            </div>

            <!-- Control Buttons -->
            <div class="col-1 d-flex flex-column justify-content-center align-items-center p-2"
                 style="min-width: 5%;">
                <button class="img-btn btn mb-2" onclick="toggleDisplay('feed-info')">
                    <img src="{% static 'network/images/info-button.png' %}" alt="info">
                </button>
                <button class="img-btn btn mb-2" onclick="toggleDisplay('feed-comments')">
                    <img src="{% static 'network/images/comment-button.png' %}" alt="Comment"/>
                </button>
                <button class="img-btn btn mb-2">
                    <a href="{% url 'network:view-recipe' recipe.id %}" target="_blank" class="a-view-recipe">
                        <img src="{% static 'network/images/new-tab.png' %}" alt="New Tab"/>
                    </a>
                </button>
            </div>

            <!-- Recipe Details -->
            <div id="feed-info" class="col-4 detail-box">
                <div>
                    <img src="{{ recipe.user.profile.image.url }}" alt="{{ recipe.user.username }}" width="25"
                         height="25" class="rounded-circle">
                    <small>{{ recipe.user.username }}</small><br>
                    <small>on {{ recipe.publication_date|date:"j F Y" }}</small>
                </div>
                <h5 class="mt-0"><strong>{{ recipe.title }}</strong></h5>
                <div class="recipe-details row">
                    <div class="col"><strong>Prep:</strong>
                        <p>{{ recipe.preparation_time }} min</p></div>
                    <div class="col"><strong>Calories:</strong>
                        <p>{{ recipe.calories }}</p></div>
                    <div class="col"><strong>Carbs:</strong>
                        <p>{{ recipe.carbs }}</p></div>
                    <div class="col"><strong>Fat:</strong>
                        <p>{{ recipe.fat }}</p></div>
                    <div class="col"><strong>Proteins:</strong>
                        <p>{{ recipe.proteins }}</p></div>
                </div>
                <p>{{ recipe.description }}</p>
                <h5 class="mt-0">Ingredients:</h5>
                <ul style="text-align: left;">
                    {% for ingredient in ingredients_list %}
                    <li>{{ ingredient }}</li>
                    {% endfor %}
                </ul>
            </div>

            <!-- Comments Section -->
            <div id="feed-comments" style="display:none" class="col-4 detail-box">
                {% if comments %}
                {% for comment in comments %}
                <div class="comment">
                    <strong>{{ comment.user.username }}</strong>
                    ({{ comment.publication_date|date:"Y-m-d H:i" }}):
                    <p>{{ comment.text }}</p>
                </div>
                {% endfor %}
                {% else %}
                <div class="text-center">
                    <p>No comments yet. Be the first to comment!</p>
                </div>
                {% endif %}
            </div>
        </div>
        {% empty %}
        <div class="text-center">
            <p>No recipes found. Check back later!</p>
        </div>
        {% endfor %}
    </div>

    <!-- Navigation buttons -->
    <div style="position: absolute; bottom: 10px; left: 50%; transform: translateX(-50%);">
        {% if page_obj.has_previous %}
        <a href="?page={{ page_obj.previous_page_number }}"
           class="btn btn-outline-primary circular-btn blink-orange" onclick="handleClick(this)">
            <img src="{% static 'network/images/left-arrow.png' %}" alt="Previous"/>
        </a>
        {% endif %}
        {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}"
           class="btn btn-outline-primary circular-btn blink-orange" onclick="handleClick(this)">
            <img src="{% static 'network/images/right-arrow.png' %}" alt="Next"/>
        </a>
        {% endif %}
    </div>
</div>

<script>
    document.getElementById('star-btn').addEventListener('click', function () {
        document.getElementById('star-img').src = "{% static 'network/images/star_selected.png' %}";
    });
    toggleDisplay();
</script>

{% endblock %}

DIAM-Project-FlavorNetwork-master/flavornetwork/network/templates/network/login.html
{% extends "network/base.html" %}
{% load static %}

{% block title %}Login{% endblock %}

{% block header %}{% endblock %}

{% block main-container-div %}main-container-login{% endblock %}
{% block feed-div %}{% endblock %}

{% block feed %}
    <div class="login-container">
        <div class="login-logo">
            <img alt="Flavor Netowrk Logo" src="{% static 'network/images/logo-2.png' %}" class="my-logo">
        </div>
        <div class="login-container-form">
            <form method="post" class="login-form">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Login</button>
                <a href="{% url 'network:register' %}" class="btn btn-primary">Register</a>
            </form>
        </div>
    </div>

{% endblock %}

DIAM-Project-FlavorNetwork-master/flavornetwork/network/templates/network/view_cookbook.html
{% extends "network/base.html" %}

{% load static %}

{% block title %}Home{% endblock %}

{% block feed %}
    <div class="home-div">
        <div class="container mt-5">
            <h2>Your Cookbook</h2>
            <div class="row">
                {% for recipe in cookbook.recipes.all %}
                    <!-- Recipe Card -->
                    <div class="col-md-4 mb-4">
                        <div class="card" >
                            <img src="{{ recipe.images.url }}" alt="{{ recipe.title }}" class="card-img-top" style="height: 400px;">
                            <div class="card-body custom-box-color" style="background-color: #f9f1e7">
                                <h5 class="card-title overflow-hidden text-truncate">{{ recipe.title }}</h5>
                                <div class="card-text overflow-hidden text-truncate" style="max-height: 3em;">
                                    {{ recipe.description }}
                                </div>
                                <br>
                                <a href="{% url 'network:view-recipe' recipe.id %}" class="custom-btn-style">View Recipe</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <a href="{% url 'network:add-recipe' %}" class="custom-btn-style mb-3">Add New Recipe</a>
        </div>
    </div>
{% endblock %}

DIAM-Project-FlavorNetwork-master/flavornetwork/network/templates/network/view_recipe.html
{% extends "network/base.html" %}

{% load static %}
{% block title %}{{ recipe.title }}{% endblock %}

{% block feed %}
    <div class="home-div">
        <h1 class="recipe-title">{{ recipe.title }}</h1><br><br>
        <div class="slider-content">
            <div class="slider-content-image">
                {% if recipe.images %}
                    <img src="{{ recipe.images.url }}" alt="{{ recipe.title }}" class="recipe-image">
                {% endif %}

                <div class="ratings" id=" {{ rating.score }}">
                    <form class="rate-form" action="" method="POST" id="{{ recipe.id }}">
                        {% csrf_token %}
                        <link rel="stylesheet"
                              href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
                        <button type="submit" class="fa fa-star star-btn" id="first"></button>
                        <button type="submit" class="fa fa-star star-btn" id="second"></button>
                        <button type="submit" class="fa fa-star star-btn" id="third"></button>
                        <button type="submit" class="fa fa-star star-btn" id="fourth"></button>
                        <button type="submit" class="fa fa-star star-btn" id="fifth"></button>
                        <br>
                    </form>
                    <div id="confirm-box"></div>
                </div>

                <div class="average-rating">
                    <strong>Average Rating:</strong>
                    <span>{{ average_rating }}</span> / 5
                </div><br>

                {% if request.user == recipe.user or request.user.is_superuser %}
                    <a href="{% url 'network:edit-recipe' recipe.id %}" class="custom-btn-style">Edit Recipe</a>
                    <a href="{% url 'network:delete-recipe' recipe.id %}" class="custom-btn-style"
                       onclick="return confirm('Are you sure you want to delete this recipe?');">Delete Recipe</a>
                {% endif %}
                {% if request.user.is_authenticated and request.user != recipe.user %}
                    {% if is_favorite %}
                        <a href="{% url 'network:remove-from-favorites' recipe.id %}" class="custom-btn-style">Remove
                            from Favorites</a>
                    {% else %}
                        <a href="{% url 'network:add-to-favorites' recipe.id %}" class="custom-btn-style">Add to
                            Favorites</a>
                    {% endif %}
                {% endif %}
            </div>
            <div class="slider-content-text">
                <div>
                    <strong>Author:</strong>
                    <p>{{ recipe.user.first_name }} {{ recipe.user.last_name }}</p>
                </div>
                <div>
                    <strong>Published:</strong>
                    <p>{{ recipe.publication_date|date:"Y-m-d" }}</p>
                </div>
                <div class="recipe-small-field">
                    <div class>
                        <strong>Prep Time:</strong>
                        <p>{{ recipe.preparation_time }} minutes</p>
                    </div>
                    <div>
                        <strong>Status:</strong>
                        <p>{{ recipe.status|capfirst }}</p>
                    </div>
                    <div>
                        <strong>Calories:</strong>
                        <p>{{ recipe.calories }}</p>
                    </div>
                    <div>
                        <strong>Carbs:</strong>
                        <p>{{ recipe.carbs }}</p>
                    </div>
                    <div>
                        <strong>Fat:</strong>
                        <p>{{ recipe.fat }}</p>
                    </div>
                    <div>
                        <strong>Proteins:</strong>
                        <p>{{ recipe.proteins }}</p>
                    </div>
                </div>
                <div>
                    <strong>Description:</strong>
                    <p>{{ recipe.description }}</p>
                </div>
                <div>
                    <strong>Ingredients:</strong>
                    <p>{{ recipe.ingredients }}</p>
                </div>
                <div>
                    <strong>Preparation Steps:</strong>
                    <p>{{ recipe.preparation_steps }}</p>
                </div>
            </div>
        </div>

        <h3>Comments</h3>
        {% for comment in comments %}
            <div class="comment">
                <strong>{{ comment.user.username }}</strong> ({{ comment.publication_date|date:"Y-m-d H:i" }}):
                <p>{{ comment.text }}</p>
            </div>
        {% empty %}
            <p>No comments yet.</p>
        {% endfor %}

        {% if request.user.is_authenticated %}
            <form method="post">
                {% csrf_token %}
                {{ comment_form.as_p }}
                <button type="submit" class="custom-btn-style">Add Comment</button>
            </form>
        {% endif %}

    </div>
    <script>startRating()</script>
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

{% endblock %}